apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wd20vpmhv-python 
  janus-idp.io/tekton: wd20vpmhv-python
  backstage.io/kubernetes-id: wd20vpmhv-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wd20vpmhv-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml