apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: wd20vpmhv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: wd20vpmhv-python 
  name: wd20vpmhv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: wd20vpmhv-python 
